[tools]
# https://github.com/oven-sh/bun/releases
bun = "1.3.4"
# https://github.com/biomejs/biome/releases
biome = "2.3.8"
# https://github.com/evilmartians/lefthook/releases
lefthook = "2.0.4"
# https://github.com/golangci/golangci-lint/releases
golangci-lint = "2.7.2"
