language: go

go:
  - master
  - "1.16"

install: true

matrix:
  allow_failures:
    - go: master
  fast_finish: true

notifications:
  email: true

before_script:
  - go get golang.org/x/lint/golint
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/go-playground/overalls
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.6

script:
  # Run all the tests with the race detector enabled
  - overalls -project=github.com/foomo/squadron -covermode=atomic -debug -- -race -v -coverpkg=./...

after_success:
  # Run linter
  - golangci-lint run ./... --exclude 'composite literal uses unkeyed fields$'
  - golint -set_exit_status $(go list ./...)